import pandas as pd
import json
import os

def load_and_merge_data():
    """Loads and merges the output CSVs from Step 8."""
    attrition_path = 'outputs/attrition_predictions.csv'
    skill_gap_path = 'outputs/skill_gap_predictions.csv'
    
    try:
        attrition_df = pd.read_csv(attrition_path)
        skill_gap_df = pd.read_csv(skill_gap_path)
    except FileNotFoundError as e:
        print(f"Error loading files: {e}")
        print("Ensure you are running this from the root directory and Step 8 has completed.")
        return None

    # Merge datasets. 
    # NOTE: Check your CSVs to confirm the exact name of the ID column (e.g., 'EmployeeID', 'emp_id')
    id_column = 'EmployeeID' if 'EmployeeID' in attrition_df.columns else attrition_df.columns[0]
    
    merged_df = pd.merge(attrition_df, skill_gap_df, on=id_column, how='inner')
    return merged_df

def generate_recommendation(row):
    """Applies rule-based logic to a single employee row."""
    
    # NOTE: You must update 'Attrition_Probability' and 'Skill_Score' to match the actual 
    # column headers generated by your ML models in Step 8.
    attrition_prob = row.get('Attrition_Probability', 0)
    skill_score = row.get('Skill_Score', 5) # Assuming 5 is a perfect score
    employee_id = int(row.iloc[0]) 

    rec = {
        "employee_id": employee_id,
        "risk_level": "Low",
        "retention_action": "No immediate action required.",
        "training_action": "Standard development track."
    }
    
    # --- RULE 1: Attrition Risk Logic ---
    if attrition_prob > 0.70:
        rec["risk_level"] = "High"
        rec["retention_action"] = "Critical flight risk. Schedule immediate 1-on-1 retention interview and review compensation."
    elif attrition_prob > 0.40:
        rec["risk_level"] = "Medium"
        rec["retention_action"] = "Moderate flight risk. Conduct a stay interview and assess workload."
        
    # --- RULE 2: Skill Gap Logic ---
    if skill_score < 3.0: 
        rec["training_action"] = "Significant skill gap. Enroll in mandatory technical upskilling bootcamp."
    elif skill_score < 4.0:
        rec["training_action"] = "Minor skill gap. Assign a senior mentor for targeted skill development."
        
    # --- RULE 3: Combined Logic ---
    if attrition_prob > 0.50 and skill_score < 3.0:
        rec["retention_action"] = "Flight risk potentially due to role mismatch or lack of training. Prioritize supportive upskilling before disciplinary action."
        
    return rec

def main():
    print("Initializing AI Recommendation Engine...")
    df = load_and_merge_data()
    
    if df is None:
        return

    recommendations = []
    
    # Process each employee
    for index, row in df.iterrows():
        recommendations.append(generate_recommendation(row))
        
    # Format as JSON for the FastAPI backend (Step 11)
    json_output = json.dumps(recommendations, indent=4)
    
    # Save the output
    os.makedirs('outputs', exist_ok=True)
    output_path = 'outputs/recommendations.json'
    
    with open(output_path, 'w') as f:
        f.write(json_output)
        
    print(f"Success! Generated {len(recommendations)} employee recommendations.")
    print(f"Data saved to: {output_path}")

if __name__ == "__main__":
    main()